# Generated by Django 5.2.6 on 2025-09-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('shoe', 'Shoe'), ('ball', 'Ball'), ('sock', 'Sock'), ('accesories', 'Accesories')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
