# Generated by Django 5.2.6 on 2025-09-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='products_solds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoe', 'Shoe'), ('ball', 'Ball'), ('sock', 'Sock'), ('accessories', 'Accessories')], default='jersey', max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
