# Generated by Django 5.2.6 on 2025-09-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('merch', 'Merchandise'), ('ticket', 'Ticket')], default='jersey', max_length=20),
        ),
    ]
